import type { NextPage } from "next";

import Image from "next/image";

import Head from "next/head";

import classes from "../styles/Home.module.css";
import UserHomepage from "../layout/UserHomepage";
import Posts from "../layout/Posts";

const Home: NextPage = () => {
  return (
    <div className={classes.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={classes.main}>
        <div className={classes["main-header"]}>
          <h3 className={classes["homepage-title"]}>Página Inicial</h3>
          <UserHomepage />
          <Posts />
        </div>
      </main>
    </div>
  );
};

export default Home;
